lookit/lookit-jspsych

- .changeset/curly-pumpkins-clean.md
- README.md
- packages/lookit-initjspsych/package.json
Currently there is two things that are now working with `unpkg.com`: 
1. The correct file ('dist/index.browser.min.js`) isn't being served.
2. If you for the correct file, the mime type is wrong. 
Adding a few lines to the `package.json` file should help to resolve these issues.
> Add unpkg config

- .changeset/clever-beans-brake.md
- .changeset/config.json
- .changeset/sharp-fishes-peel.md
- README.md
- package-lock.json
- package.json
- packages/lookit-api/jest.config.cjs
- packages/lookit-api/package.json
- packages/lookit-api/rollup.config.mjs
- packages/lookit-api/src/index.spec.ts
- packages/lookit-api/src/index.ts
- packages/lookit-api/src/types.ts
- packages/lookit-api/src/utils.ts
- packages/lookit-api/tsconfig.json
- packages/lookit-helpers/jest.config.cjs
- packages/lookit-helpers/package.json
- packages/lookit-helpers/rollup.config.mjs
- packages/lookit-helpers/src/index.spec.ts
- packages/lookit-helpers/src/index.ts
- packages/lookit-helpers/src/types.ts
- packages/lookit-helpers/tsconfig.json
- packages/lookit-initjspsych/package.json
This PR adds two packages to our jspsych mono repo.  Lookit-API will contain an implementation of Lookit's restful API and Lookit-helpers to provide functions to users to get access to child data and past session data for this child in this study. 
To help develop using the lookit restful API, I added a package to containerize the retrieval of data.  This package should contain any implementation of a lookit endpoint.  This package does not contain every available endpoint, just the ones needed for this project up to this point.  At this time I have no intention of releasing this package to NPM.  
The "initJSPysch" package needs to be updated using this package. 
Users are used to having access to child data and past sessions when running an experiment using EFP's generator.  This package …
> Child and past sessions data

- .changeset/config.json
This PR removes the `lookit-api` package from `ignore` in the changesets config. We were trying to use the ignore parameter to avoid publishing the `@lookit/lookit-api` package, since it doesn't need to be published, but this is causing the following error in the GH release step "Create Release Pull Request or Publish Packages"
>  /opt/hostedtoolcache/node/20.11.1/x64/bin/npx changeset publish
> error ValidationError: Some errors occurred when validating the changesets config:
> error The package "@lookit/lookit-helpers" depends on the ignored package "@lookit/lookit-api", but "@lookit/lookit-helpers" is not being ignored. Please add "@lookit/lookit-helpers" to the `ignore` option.
We can consider alternative solutions, or just leave this as is to continue publishing the …
> remove lookit-api from ignore in changesets config

- .changeset/config.json
- .eslintrc.js
- .prettierrc
- README.md
- package-lock.json
- package.json
- packages/lookit-api/package.json
- packages/lookit-api/tsconfig.json
- packages/lookit-helpers/package.json
- packages/lookit-helpers/tsconfig.json
- packages/lookit-initjspsych/package.json
- packages/lookit-initjspsych/tsconfig.json
Closes  #14
This cleans and normalizes the `package.json` files across this mono repo's packages. 
To reset the version of these packages we'll need to do the following things:
1. Change package files to reflect the intended version.  For our case here, we're setting all packages to version `0.0.1`.
2. Remove all [packages from NPM](https://www.npmjs.com/search?q=%40lookit).
3. Make sure there are no `changeset` files for these packages.
If the above has been done, then when we attempt to publish these packages they should be all at version `0.0.1`.  Additionally, we'll have to update the version in the Django project `lookit-api`.
> Suggested package updates

- .github/workflows/build.yml
- .github/workflows/release.yml
- packages/lookit-helpers/package.json
Almost unnecessary updates to GitHub actions.  `setup-node` is now at version 4.
Should I increment the version of helpers to fix the spelling mistake?
No `changset` is needed.  No packages will be affected by this change.
> Update setup-node version

- rollup.mjs
I was running across an issue where packages couldn't reference another package.  This was resolved by adding back in the CommonJS builds.  Easy fix, embarrassing mistake.
> Remove iife only build

- jest.cjs
- jest.text.loader.js
- package-lock.json
- packages/record/package.json
- packages/record/rollup.config.mjs
- packages/record/src/recorder.ts
- packages/record/src/stop.ts
- packages/record/src/string-import.d.ts
- packages/record/src/templates/uploading-video.mustache
- packages/record/src/templates/webcam-feed.mustache
- packages/record/tsconfig.json
As a developer, writing HTML as strings sucks.  This PR adds a template engine to assist HTML development within JavaScript.  
I unilaterally decided on [Mustache](https://mustache.github.io/) and the JavaScript implementation [`mustache.js`](https://github.com/janl/mustache.js).  To support the `mustache.js` package, I added the ability to "import" template files as strings.  This should provide an easy path to future HTML development.  This is currently only in the `@lookit/record` package, but it could easily be added to any package.  
See [the specification documentation](https://mustache.github.io/) for details on templates.
1. Add your template to the "templates" directory.  Use the "mustache" extension.
2. Import template (e.g. `import templateName from …
> Mustache template engine

- README.md
I've added some (clunky) language about how docs are used, updated, and organized.  As always, I welcome any changes to the documentation language.
> Add text about how to use the doc local dev server.

- .changeset/sharp-toes-learn.md
- packages/data/src/environment.d.ts
- packages/data/src/lookitS3.ts
This PR changes the AWS S3 environment variable names used for uploading to the jsPsych video bucket. We used the same environment variable names that are used for EFP (RecordRTC) video uploading, so we need different ones to avoid conflicting variable names in the lookit-api environment.
For local development - remember to also change the variable names in `packages/data/.env`.
> Change AWS S3 env var names

- .changeset/silver-pigs-develop.md
- packages/record/src/consentVideo.spec.ts
- packages/record/templates/playback-feed.hbs
This PR is a fix for a small bug where the playback of the recorded consent video was muted by default.
> Unmuted recorded consent playback

- .changeset/nice-hats-sing.md
- rollup.mjs
At this point, we accept that AWS (and its dependencies) will have some circular dependency warnings with Rollup. To hide them without also hiding warnings we'd like to address, I've created a list of strings to identify the warnings we've already run across.  Additionally, I've changed "warnings" to "errors."  This will help catch issues with Rollup before they accidentally end up in production.
> Hide circular dependency warnings

- .readthedocs.yml
- makefile
This is the config for readthedocs.org.  Note:  I am going to push this without review.
> Config for readthedocs deploy

- tests/exit_survey_parameters.js
- tests/survey_consent_no_recording.js
- tests/video_consent_session_recording.js
- tests/video_consent_trial_recording.js
This PR adds a `tests` directory for jsPsych experiment code that can be used for testing and updated as needed. We should include test experiments for each combination of experiment scenarios (combinations of our custom plugins/extensions and parameters) that we need to test. These are meant to be 'minimum viable jsPsych-lookit experiments', i.e. they include all parts of a valid CHS experiment, but with a basic placeholder trial for the jsPsych task. Here is what is included:
- `exit_survey_parameters`: Uses the non-default values for the exit survey parameters.
- `survey_consent_no_recording`: Uses a survey consent trial and does not do any recording.
- `video_consent_session_recording`: Video consent trial with session recording.
- `video_consent_trial_recording`: Video consent trial …
> Add test experiments

- .gitignore
- .readthedocs.yml
- makefile
- mkdocs.yml
- packages/record/README.md
- packages/templates/README.md
- poetry.lock
- pyproject.toml
Now that the "jsPsych" docs are up on read the docs, I wanted to make a few changes for clarity and simplicity.  Also, I cleaned the "MkDocs" config file of unnecessary comments.
> Readthedocs For custom jsPsych trials

- .changeset/cold-chairs-confess.md
- .changeset/strange-bottles-invent.md
- .gitignore
- packages/record/scss/consent-video-trial.scss
- packages/style/src/index.css
- packages/templates/hbs/consent-garden.hbs
- packages/templates/src/consentVideoTemplate.ts
- packages/templates/src/index.spec.ts
- packages/templates/src/utils.ts
Add Garden's consent template to project.
> Consent garden template

- .readthedocs.yml
- makefile
- poetry.lock
- pyproject.toml
Whoops!  Readthedocs doesn't support Python 3.13. Moving version back to 3.12.
> readthedocs doesn't support 3.13.  Rollback to 3.12

- .changeset/rotten-cars-swim.md
- packages/record/src/consentVideo.spec.ts
- packages/record/src/consentVideo.ts
- packages/record/src/index.spec.ts
- packages/record/src/recorder.spec.ts
- packages/record/src/recorder.ts
- packages/record/src/start.ts
- packages/record/src/trial.ts
- packages/record/src/types.ts
This PR updates the video file names in the `record` package so that they match the format used by EFP and expected by the lookit-api and and the AWS S3-Lambda trigger. 
- Consent videos: `consent-videoStream_{study}_{frame_id}_{response}_{timestamp}_{random_digits}.webm`
- Non-consent videos: `videoStream_{study}_{frame_id}_{response}_{timestamp}_{random_digits}.webm`
This naming system requires two arguments from the plugin that calls `recorder.start`: 
1. whether or not this is a consent recording, which is used for the prefix
2. the "trial_type" (plugin name), which is used to create the `frame_id` value
The `frame_id` value is the same one that lookit-jspsych uses in the response `sequence` field, and that's used in the lookit-api to identify trials. The format is: …
> Video file names in standard format

- .changeset/mean-llamas-cheat.md
- .github/workflows/build.yml
- README.md
- packages/data/rollup.config.mjs
- packages/record/rollup.config.mjs
- packages/templates/rollup.config.mjs
The production build didn't include environment variables. Where a value, such as DEBUG, could be "undefined," Rollupjs would leave it as "process.env.DEBUG." This throws an error in the browser. To fix this issue, we generated an environment file before the production build. 
Additionally, I configured Rollupjs to look for the environment file in a central location at the root of the mono repo.
> Production dotenv

- .changeset/smart-books-scream.md
- packages/record/src/consentVideo.ts
Fixes #84
This PR adds a default value (empty array) for the `additional_segments` parameter in the video consent plugin. The missing default value was causing jsPsych to produce a runtime error when this optional parameter was omitted from the trial configuration.
This also moves the 'text' property in the parameter info object into the additional segments `nested` object, which is what defines the structure of the "COMPLEX" (object) parameter type. In this case, the `additional_segments` parameter can be an array of objects, where each object can have a "title" (string) and "text" (string) property.
**Note**
The default value for this parameter could also be: `[{title: "", text: ""}]`. I'm not sure whether it matters?
**Screenshots**
After this fix, the video consent plugin runs without …
> Add default for optional `additional_segments` parameter in video consent

- .changeset/beige-horses-beam.md
- .changeset/hip-drinks-pump.md
- .github/workflows/build.yml
- .github/workflows/release.yml
- .husky/pre-commit
- package-lock.json
- package.json
- packages/lookit-initjspsych/package.json
- packages/style/src/index.css
- packages/surveys/package.json
Just before releasing the latest round of packages, I noticed some inconsistencies with our dependencies and versioning.
- Changeset will bump a major version for packages with a peer dependency that was also changed.  See relevant [documentation](https://github.com/changesets/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies).
- For two packages, `@lookit/data` wasn't set as a peer dependency. 
- The CSS file wasn't generated/committed in the style package. 
This PR covers a few seemingly disjoint solutions.  I'll list them here. 
- To make commits faster, I added "lint-staged" to only lint the staged files. 
- I mistakenly put the step that generates the `.env` file in the wrong script.  This has been resolved. 
- Move `@lookit/data` to peer dependency in all …
> Surveys peer deps

- .changeset/plenty-carpets-yell.md
- package-lock.json
- packages/lookit-initjspsych/package.json
NPM has already seen v1.0.0 of lookit-initjspsych and versions up to 1.0.5. NPM won't let you re-publish a package with a known version.  This PR will move this package's version to 1.0.6.
> Bump initjspsych version

- .changeset/purple-phones-count.md
- packages/record/README.md
- packages/surveys/README.md
This PR adds the `locale` parameter to the `survey` package docs, and makes a minor change to the `record` docs.
The `locale` parameter was added to the `survey` plugins here in #97 and #98 but those PRs do not include the docs update.
Merging this without review.
> Add `locale` to `survey` docs

- .changeset/khaki-bobcats-pump.md
- package-lock.json
- packages/surveys/package.json
- packages/surveys/src/consentSurvey.ts
- packages/surveys/src/errors.ts
- packages/surveys/src/exitSurvey.ts
- packages/surveys/src/utils.spec.ts
- packages/surveys/src/utils.ts
- packages/templates/src/exitSurveyTemplate.ts
Basically, set [SurveyJS Localization](https://surveyjs.io/form-library/documentation/survey-localization) parameter.
Update documentation for exit survey.
> SurveyJS locale

- .changeset/shiny-walls-refuse.md
- package-lock.json
- packages/surveys/src/consentSurvey.ts
This PR fixes the 'missing locale' error that is thrown when running a consent survey trial with no `locale` parameter value. This parameter should be optional, and jsPsych should use the default value in the plugin's parameter info if no value is set by the user.
The problem was that our ConsentSurveyPlugin class was still using the info from the jsPsych `survey` plugin, which we are extending with this plugin.
> Fix the 'missing locale' error in the consentSurvey plugin

- .changeset/itchy-books-judge.md
- package-lock.json
- packages/lookit-initjspsych/src/utils.spec.ts
- packages/lookit-initjspsych/src/utils.ts
Fixes #107 
This PR modifies the experiment `on_finish` logic for throwing a sequence error so that the error is only thrown if both the response sequence is empty (no previous trial data saved) AND the data array passed in from jsPsych is empty (no experiment data). This change prevents an error that is currently thrown when the experiment has only one trial.
> Fix error in single-trial experiments

- .changeset/itchy-books-judge.md
- .changeset/thin-oranges-collect.md
- package-lock.json
- packages/lookit-initjspsych/src/utils.spec.ts
- packages/lookit-initjspsych/src/utils.ts
The exit URL was still interrupting the final Response update.  This PR uses Promise's "Then"s to make the calls happen in order.
> Exit URL fix

- .changeset/mighty-islands-collect.md
- package-lock.json
- packages/data/package.json
- packages/data/rollup.config.mjs
- packages/data/src/utils.spec.ts
- packages/data/src/utils.ts
- packages/data/tsconfig.json
- packages/lookit-initjspsych/package.json
- packages/record/package.json
- packages/record/rollup.config.mjs
- packages/record/scss/index.scss
- packages/record/src/recorder.spec.ts
- packages/style/package.json
- packages/style/scss/index.scss
- packages/style/src/index.css
- packages/surveys/package.json
- packages/surveys/scss/index.scss
- packages/templates/package.json
- packages/templates/rollup.config.mjs
- rollup.mjs
This PR updates all packages. There's a large change with the `@lookit/data` package. It (specifically `@aws-sdk/s3-client`) doesn't work well with Rollup.  I was unable to get it to build with jsPsych's config, so put together a custom config.
> Update jspsych config

- mkdocs.yml
- package-lock.json
- poetry.lock
When attempting to review the docs in jsPsych, there was a warning about a README file in a `node_modules` directory. This PR updates the config to ignore this directory.
Additionally, there was an update to the Poetry lock file.
> Update mkdocs config to exclude `node_modules`

- .changeset/tricky-islands-visit.md
- mkdocs.yml
- package-lock.json
- packages/record/README.md
- packages/templates/README.md
This PR makes some minor changes to the CHS Record package docs:
- Adds separate sections for the start/stop recording plugins. This makes it easier to link to them from other places, and it will be useful when more parameters are added (e.g. upload time limit for stop recording).
- Standardizes the sections: 
- adds "plugin"/"extension" to headers
- subsections: 1) parameters, 2) example
- Adds the 'admonitions' markdown extension.
- Adds note about requiring a video config trial before any other recording.
- Adds note about not using trial/session recording with other trials/extensions that use the webcam.
- Fixes link to video-config section from templates docs.
Video consent:
Trial recording:
Session recording:
> Record package docs updates

- _custom_theme/css/jspsych_docs.css
- _custom_theme/js/links_in_new_tab.js
- _custom_theme/main.html
- mkdocs.yml
- poetry.lock
Partially fixes https://github.com/lookit/lookit-docs/issues/435
This PR adds the custom 'tabs' at the top of the CHS jsPsych navigation menu, which link to our other docs sites. These tabs match the others that we're using in the lookit-api and EFP docs.
The customization files are in `_custom_theme`. I've also updated the `mkdocs.yml` file to use this customization and to remove the unnecessary sections in the navigation menu.
With these changes:
Current version, for reference:
> Add navigation tabs to docs

- .changeset/calm-tomatoes-warn.md
- packages/record/src/recorder.spec.ts
- packages/record/src/recorder.ts
- packages/record/src/videoConfig.spec.ts
- packages/record/src/videoConfig.ts
Fixes #126
This fixes a problem with video recordings not playing in some browsers. The problem is due to initializing a recorder without specifying the codecs (we had the same thing happen in EFP: https://github.com/lookit/ember-lookit-frameplayer/pull/365). To fix this, we just need to specify the mimeType codecs value as part of the recording options when the recorder is initialized. This PR does the following:
- In the video config plugin, adds a `getCompatibleMimeType` method to check mime type compatibility and get the first compatible type from the list. This mime type string must be specified when the plugin initializes the jsPsych recorder via `jsPsych.pluginAPI.initializeCameraRecorder`.
- In the recorder class, gets the mime type value from the existing recorder and stores it. …
> Fix video recording playback issues

- package-lock.json
- packages/lookit-initjspsych/fixtures/TestPlugin.ts
- packages/lookit-initjspsych/jest.config.cjs
- packages/lookit-initjspsych/package.json
- packages/lookit-initjspsych/src/errors.ts
- packages/lookit-initjspsych/src/index.spec.ts
- packages/lookit-initjspsych/src/index.ts
- packages/lookit-initjspsych/src/types.ts
- packages/lookit-initjspsych/src/utils.spec.ts
- rollup.mjs
Fixes #130 
This PR fixes the problem with CHS jsPsych studies throwing an error when the experiment contains a timeline node (object with a "timeline" property). The error occurs because are iterating through the experiment timeline to find all of the trial types (to call their chsData methods, and probably for other reasons in the future), and we are throwing errors when the "type" key is missing or null/undefined. 
This PR fixes the problem by implementing a recursive search of timeline arrays to check for any plugin types in trial objects. Errors are still thrown if the "type" property exists but its value is null/undefined. But now, instead of throwing an error when the "type" property is missing, it also checks to see if the element is an array or timeline node (i.e. has a …
> Fix timeline node error

- .changeset/blue-seals-warn.md
- .changeset/calm-tomatoes-warn.md
- .changeset/khaki-flowers-prove.md
- .changeset/tricky-islands-visit.md
- packages/record/src/consentVideo.ts
This addresses part of #133 but probably doesn't fully solve the problem.
After a consent video recording starts and then the recording is stopped, the playback button was enabled before the recorder's stop event handler was triggered. It might've been possible for a user to try to playback a video whose source URL had not been created yet. (Simulating this sequence event with a `setTimeout` around the `URL.createObjectURL` line reproduces the plugin's stuck state, and this PR fixes that problem).  
This PR changes the recording stop event handler so that the playback button is only enabled after the recorder is fully stopped. This helps prevent a race condition between creating the recording URL and trying to replay it. However, if something goes wrong with the recording URL creation …
> Wait to enable playback button until after recording URL is created

- .readthedocs.yml
This is an attempt at fixing #160 
The lookit-jspsych RTD builds are failing following the switch from `poetry` to `uv`. I think the issue is with this line: `VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --frozen`, which was a poetry-specific fix for telling poetry to use the RTD virtual environment. My current theory is that `uv` doesn't respect this directive and installs into a local `.venv` instead of using the RTD as it should. 
If this theory is correct, then it might be fixed by using the same command `uv sync --frozen` along with the [`active` flag](https://docs.astral.sh/uv/reference/cli/#uv-run--active), which tells uv to install into the active venv instead of creating one.
> RTD build: don't pass venv arg, use `active` flag

- .readthedocs.yml
This is another attempt at fixing #160. PR #161 did not fix the issue - `uv` is still creating its own virtual environment, despite the `active` flag. This time I'm trying to manually activate the RTD venv before calling `uv sync --frozen --active`.
> RTD build: try activating the RTD venv before `uv sync`

- .readthedocs.yml
This is another attempt at fixing https://github.com/lookit/lookit-jspsych/issues/160. PR https://github.com/lookit/lookit-jspsych/pull/162 did not fix the issue because `source` was not available in the RTD shell. So we can try using the dot syntax to activate the virtual environment.
> RTD build: doesn't support `source` so try dot syntax

- .changeset/many-onions-pump.md
- .changeset/poor-walls-relate.md
- packages/lookit-initjspsych/src/errors.ts
- packages/lookit-initjspsych/src/index.spec.ts
- packages/lookit-initjspsych/src/index.ts
- packages/lookit-initjspsych/src/utils.spec.ts
- packages/lookit-initjspsych/src/utils.ts
This PR partly addresses #170 but should not close that issue.
Our custom `on_data_update` function now sends _all of the experiment data_ to the lookit-api end point on each update, rather than retrieving the existing data from lookit-api and appending the new data to that. 
This solution is more robust to intermittent data saving failures/corruption during the experiment, because we are saving the 'ground truth' copy of the data and not appending to our existing data copy, which could be missing data if any previous API requests failed. And there should not changes to the network load (we were already retrieving all of the data and sending all of it back on each update - now we are still sending it all back but eliminating the initial data retrieval).
This PR also includes all changes …
> Modify jsPsych data handling
